#!/usr/bin/env python3
"""
olmocr PDF Processing Task

This script runs inside an ECS container to process PDFs using Allen AI's olmocr model.
It uses the olmocr pipeline to convert PDFs to clean Markdown.

GPU required (g4dn.xlarge or better). Uses vLLM for inference with the 7B parameter VLM.

Environment Variables:
    JOB_ID: Unique job identifier
    S3_BUCKET: S3 bucket name
    S3_INPUT_KEY: S3 key for input PDF
    DYNAMODB_TABLE: DynamoDB table name for job tracking
    PROMPT: Optional custom prompt for processing
"""

import os
import sys
import tempfile
import logging
import subprocess
from pathlib import Path
from datetime import datetime, timezone

# Force offline mode - model is pre-downloaded, no need to check HuggingFace
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"

import boto3

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def get_required_env(key: str) -> str:
    """Get required environment variable or exit."""
    value = os.environ.get(key)
    if not value:
        logger.error(f"Missing required environment variable: {key}")
        sys.exit(1)
    return value


def update_job_status(
    dynamodb,
    table_name: str,
    job_id: str,
    status: str,
    substatus: str = None,
    s3_result_key: str = None,
    error: str = None
):
    """Update job status in DynamoDB."""
    table = dynamodb.Table(table_name)

    update_expr = "SET #status = :status, completed_at = :completed_at"
    expr_attr_names = {"#status": "status"}
    expr_attr_values = {
        ":status": status,
        ":completed_at": datetime.now(timezone.utc).isoformat()
    }

    if substatus:
        update_expr += ", substatus = :substatus"
        expr_attr_values[":substatus"] = substatus

    if s3_result_key:
        update_expr += ", s3_result_key = :result_key"
        expr_attr_values[":result_key"] = s3_result_key

    if error:
        update_expr += ", #error = :error"
        expr_attr_names["#error"] = "error"
        expr_attr_values[":error"] = error

    table.update_item(
        Key={"job_id": job_id},
        UpdateExpression=update_expr,
        ExpressionAttributeNames=expr_attr_names,
        ExpressionAttributeValues=expr_attr_values
    )
    logger.info(f"Updated job {job_id} to status: {status}" + (f" ({substatus})" if substatus else ""))


def process_pdf_with_olmocr(input_pdf: Path, output_dir: Path, custom_prompt: str = None) -> str:
    """Process PDF with olmocr pipeline.

    Args:
        input_pdf: Path to input PDF file
        output_dir: Directory for output files
        custom_prompt: Optional custom prompt (currently not used by olmocr pipeline)

    Returns:
        str: Markdown content
    """
    import torch

    if not torch.cuda.is_available():
        raise RuntimeError("olmocr requires CUDA GPU support")

    gpu_name = torch.cuda.get_device_name(0)
    gpu_memory = torch.cuda.get_device_properties(0).total_memory / 1e9
    logger.info(f"GPU: {gpu_name}")
    logger.info(f"GPU Memory: {gpu_memory:.1f} GB")

    logger.info(f"Processing PDF with olmocr: {input_pdf}")

    # Run olmocr pipeline
    # The pipeline outputs markdown files to output_dir/markdown/
    cmd = [
        "python3", "-m", "olmocr.pipeline",
        str(output_dir),
        "--markdown",
        "--pdfs", str(input_pdf),
        "--model", "allenai/olmOCR-7B-0225-preview",
    ]

    logger.info(f"Running command: {' '.join(cmd)}")

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=1800  # 30 minute timeout
    )

    if result.returncode != 0:
        logger.error(f"olmocr pipeline failed: {result.stderr}")
        raise RuntimeError(f"olmocr pipeline failed: {result.stderr}")

    logger.info(f"olmocr output: {result.stdout}")

    # Find the generated markdown file
    markdown_dir = output_dir / "markdown"
    if not markdown_dir.exists():
        # Check for output in base directory
        markdown_files = list(output_dir.glob("*.md"))
    else:
        markdown_files = list(markdown_dir.glob("*.md"))

    if not markdown_files:
        logger.warning("No markdown files generated by olmocr")
        # Try to find any text output
        txt_files = list(output_dir.rglob("*.txt"))
        if txt_files:
            return txt_files[0].read_text(encoding="utf-8")
        return ""

    # Combine all markdown files if multiple
    markdown_content = ""
    for md_file in sorted(markdown_files):
        content = md_file.read_text(encoding="utf-8")
        if markdown_content:
            markdown_content += "\n\n---\n\n"
        markdown_content += content
        logger.info(f"Read markdown from {md_file.name}: {len(content)} chars")

    return markdown_content


def main():
    """Main processing logic."""
    # Get required environment variables
    job_id = get_required_env("JOB_ID")
    bucket_name = get_required_env("S3_BUCKET")
    input_key = get_required_env("S3_INPUT_KEY")
    table_name = get_required_env("DYNAMODB_TABLE")

    # Get optional custom prompt (empty string means use default)
    custom_prompt = os.environ.get("PROMPT", "").strip() or None

    logger.info(f"Starting olmocr job {job_id}")
    logger.info(f"Input: s3://{bucket_name}/{input_key}")
    if custom_prompt:
        logger.info(f"Custom prompt provided: {custom_prompt}")

    # Initialize AWS clients
    s3 = boto3.client("s3")
    dynamodb = boto3.resource("dynamodb")

    try:
        # Update status to processing - downloading
        update_job_status(dynamodb, table_name, job_id, "processing", substatus="downloading")

        # Create temporary directory for processing
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            input_pdf = temp_path / "input.pdf"
            output_dir = temp_path / "output"
            output_dir.mkdir()

            # Download PDF from S3
            logger.info("Downloading PDF from S3...")
            s3.download_file(bucket_name, input_key, str(input_pdf))
            logger.info(f"Downloaded PDF: {input_pdf.stat().st_size} bytes")

            # Update substatus - loading models (olmocr loads models internally)
            update_job_status(dynamodb, table_name, job_id, "processing", substatus="loading_models")

            # Update substatus - converting
            update_job_status(dynamodb, table_name, job_id, "processing", substatus="converting")

            # Process with olmocr
            markdown_content = process_pdf_with_olmocr(input_pdf, output_dir, custom_prompt)

            # Generate result S3 key
            # Extract user_id from input_key (format: {user_id}/{job_id}.pdf)
            user_id = input_key.split("/")[0]
            md_result_key = f"{user_id}/{job_id}-result.md"

            # Update substatus - uploading
            update_job_status(dynamodb, table_name, job_id, "processing", substatus="uploading")

            # Write and upload Markdown result
            md_file = temp_path / "output.md"
            md_file.write_text(markdown_content, encoding="utf-8")
            logger.info(f"Uploading Markdown result to s3://{bucket_name}/{md_result_key}")
            s3.upload_file(str(md_file), bucket_name, md_result_key)

            logger.info("Upload complete")

            # Update job status to completed
            update_job_status(
                dynamodb,
                table_name,
                job_id,
                "completed",
                s3_result_key=md_result_key
            )

            logger.info(f"Job {job_id} completed successfully")

    except Exception as e:
        logger.error(f"Job {job_id} failed: {str(e)}", exc_info=True)

        # Update job status to failed
        try:
            update_job_status(
                dynamodb,
                table_name,
                job_id,
                "failed",
                error=str(e)
            )
        except Exception as update_error:
            logger.error(f"Failed to update job status: {str(update_error)}")

        sys.exit(1)


if __name__ == "__main__":
    main()
