"""
API Stack: REST API Gateway with Cognito authorization and Rust Lambda functions.

This stack creates the API layer for job submission and status queries.
"""

from aws_cdk import (
    Stack,
    Duration,
    aws_apigateway as apigw,
    aws_cognito as cognito,
    aws_lambda as lambda_,
    aws_iam as iam,
    aws_logs as logs,
    aws_ssm as ssm,
)
from constructs import Construct

from backend.stack_config import CONFIG


class ApiStack(Stack):
    """API Gateway and Lambda functions for job management.

    Creates:
    - REST API Gateway with Cognito User Pool Authorizer
    - Lambda functions for job submission and status queries
    - API routes with proper CORS configuration
    - CloudWatch log groups for API and Lambda logs
    """

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # Get dependencies from SSM
        dynamodb_table_name = ssm.StringParameter.value_for_string_parameter(
            self, CONFIG.SSM_DYNAMODB_TABLE_NAME
        )
        state_machine_arn = ssm.StringParameter.value_for_string_parameter(
            self, "/pdf-models/marker/state-machine-arn"
        )
        user_pool_id = ssm.StringParameter.value_for_string_parameter(
            self, CONFIG.SSM_COGNITO_USER_POOL_ID
        )

        # Create CloudWatch log groups for Lambdas
        submit_job_log_group = logs.LogGroup(
            self,
            "SubmitJobLogGroup",
            log_group_name=f"/aws/lambda/{CONFIG.PROJECT_NAME}-submit-job",
            retention=logs.RetentionDays.ONE_WEEK,
        )

        get_job_log_group = logs.LogGroup(
            self,
            "GetJobLogGroup",
            log_group_name=f"/aws/lambda/{CONFIG.PROJECT_NAME}-get-job",
            retention=logs.RetentionDays.ONE_WEEK,
        )

        # Create Lambda execution role for submit-job
        submit_job_role = iam.Role(
            self,
            "SubmitJobLambdaRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaBasicExecutionRole"
                )
            ],
        )

        # Grant DynamoDB permissions to submit-job role
        submit_job_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=["dynamodb:PutItem"],
                resources=[
                    f"arn:aws:dynamodb:{self.region}:{self.account}:table/{dynamodb_table_name}"
                ],
            )
        )

        # Grant Step Functions permissions to submit-job role
        submit_job_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=["states:StartExecution"],
                resources=[state_machine_arn],
            )
        )

        # Create Lambda execution role for get-job
        get_job_role = iam.Role(
            self,
            "GetJobLambdaRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaBasicExecutionRole"
                )
            ],
        )

        # Grant DynamoDB permissions to get-job role
        get_job_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=["dynamodb:GetItem", "dynamodb:Query"],
                resources=[
                    f"arn:aws:dynamodb:{self.region}:{self.account}:table/{dynamodb_table_name}",
                    f"arn:aws:dynamodb:{self.region}:{self.account}:table/{dynamodb_table_name}/index/*",
                ],
            )
        )

        # Create submit-job Lambda function
        # NOTE: Lambda code must be built first using: make lambda-build
        # The bootstrap binary is generated by cargo-lambda build
        submit_job_function = lambda_.Function(
            self,
            "SubmitJobFunction",
            function_name=f"{CONFIG.PROJECT_NAME}-submit-job",
            runtime=lambda_.Runtime.PROVIDED_AL2023,
            handler="bootstrap",
            code=lambda_.Code.from_asset("lambdas/submit-job/target/lambda/submit-job"),
            architecture=lambda_.Architecture.ARM_64,
            role=submit_job_role,
            timeout=Duration.seconds(30),
            memory_size=256,
            log_group=submit_job_log_group,
            environment={
                "DYNAMODB_TABLE_NAME": dynamodb_table_name,
                "STATE_MACHINE_ARN": state_machine_arn,
            },
        )

        # Create get-job Lambda function
        # NOTE: Lambda code must be built first using: make lambda-build
        # The bootstrap binary is generated by cargo-lambda build
        get_job_function = lambda_.Function(
            self,
            "GetJobFunction",
            function_name=f"{CONFIG.PROJECT_NAME}-get-job",
            runtime=lambda_.Runtime.PROVIDED_AL2023,
            handler="bootstrap",
            code=lambda_.Code.from_asset("lambdas/get-job/target/lambda/get-job"),
            architecture=lambda_.Architecture.ARM_64,
            role=get_job_role,
            timeout=Duration.seconds(30),
            memory_size=256,
            log_group=get_job_log_group,
            environment={
                "DYNAMODB_TABLE_NAME": dynamodb_table_name,
            },
        )

        # Create API Gateway
        api = apigw.RestApi(
            self,
            "JobsApi",
            rest_api_name=f"{CONFIG.PROJECT_NAME}-api",
            description="PDF Models API for job submission and status queries",
            deploy_options=apigw.StageOptions(
                stage_name="v1",
                # Logging disabled - requires CloudWatch Logs role ARN in account settings
                # logging_level=apigw.MethodLoggingLevel.INFO,
                # data_trace_enabled=True,
                metrics_enabled=True,
            ),
            default_cors_preflight_options=apigw.CorsOptions(
                allow_origins=apigw.Cors.ALL_ORIGINS,
                allow_methods=apigw.Cors.ALL_METHODS,
                allow_headers=["Content-Type", "Authorization"],
                max_age=Duration.hours(1),
            ),
        )

        # Create Cognito User Pool Authorizer
        user_pool = cognito.UserPool.from_user_pool_id(
            self,
            "UserPool",
            user_pool_id,
        )

        authorizer = apigw.CognitoUserPoolsAuthorizer(
            self,
            "CognitoAuthorizer",
            cognito_user_pools=[user_pool],
        )

        # Create API resources: /v1/models/{model}/jobs
        v1 = api.root.add_resource("v1")
        models = v1.add_resource("models")
        model = models.add_resource("{model}")
        jobs = model.add_resource("jobs")
        job_id = jobs.add_resource("{job_id}")

        # Integration for submit-job Lambda
        submit_job_integration = apigw.LambdaIntegration(
            submit_job_function,
            proxy=True,
        )

        # Integration for get-job Lambda
        get_job_integration = apigw.LambdaIntegration(
            get_job_function,
            proxy=True,
        )

        # Add POST /v1/models/{model}/jobs - submit job
        jobs.add_method(
            "POST",
            submit_job_integration,
            authorizer=authorizer,
            authorization_type=apigw.AuthorizationType.COGNITO,
        )

        # Add GET /v1/models/{model}/jobs - list jobs
        jobs.add_method(
            "GET",
            get_job_integration,
            authorizer=authorizer,
            authorization_type=apigw.AuthorizationType.COGNITO,
        )

        # Add GET /v1/models/{model}/jobs/{job_id} - get single job
        job_id.add_method(
            "GET",
            get_job_integration,
            authorizer=authorizer,
            authorization_type=apigw.AuthorizationType.COGNITO,
        )

        # Export API endpoint to SSM
        ssm.StringParameter(
            self,
            "ApiEndpoint",
            parameter_name="/pdf-models/api/endpoint",
            string_value=api.url,
            description="API Gateway endpoint URL",
        )

        # Export API ID to SSM
        ssm.StringParameter(
            self,
            "ApiId",
            parameter_name="/pdf-models/api/id",
            string_value=api.rest_api_id,
            description="API Gateway REST API ID",
        )
